# Generated by Django 5.1.4 on 2025-01-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('laptopid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('ramSize', models.IntegerField()),
                ('architecture', models.IntegerField()),
                ('CPUbrand', models.CharField(max_length=255)),
                ('CPUName', models.CharField(max_length=255)),
                ('CPUGen', models.CharField(max_length=255)),
                ('ramType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RamDetails',
            fields=[
                ('ramid', models.AutoField(primary_key=True, serialize=False)),
                ('shopeeListing', models.CharField(max_length=255)),
                ('ramLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLaptop',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('ramSize', models.IntegerField()),
                ('architecture', models.IntegerField()),
                ('CPUbrand', models.CharField(max_length=255)),
                ('CPUName', models.CharField(max_length=255)),
                ('CPUGen', models.CharField(max_length=255)),
                ('ramType', models.CharField(max_length=255)),
                ('ramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primaryApp.ramdetails')),
            ],
        ),
    ]
