# Generated by Django 5.1.4 on 2025-01-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('laptopid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('productLine', models.CharField(max_length=255)),
                ('CPU', models.CharField(max_length=255)),
                ('ramSize', models.CharField(max_length=255)),
                ('ramType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RamDetails',
            fields=[
                ('ramid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('ramType', models.CharField(max_length=255)),
                ('ramSize', models.CharField(max_length=255)),
                ('ramLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLaptop',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('ramSize', models.IntegerField()),
                ('architecture', models.IntegerField()),
                ('CPUbrand', models.CharField(max_length=255)),
                ('CPUName', models.CharField(max_length=255)),
                ('CPUGen', models.CharField(max_length=255)),
                ('ramType', models.CharField(max_length=255)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_laptops', to='primaryApp.laptopdetails')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_laptops', to='primaryApp.ramdetails')),
            ],
        ),
    ]
