# Generated by Django 5.1.4 on 2025-02-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaryApp', '0002_alter_userlaptop_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramdetails',
            name='ramLink',
            field=models.URLField(max_length=255),
        ),
    ]
