# Generated by Django 5.1.4 on 2025-02-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primaryApp', '0003_alter_ramdetails_ramlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramdetails',
            name='ramLink',
            field=models.URLField(max_length=300),
        ),
    ]
